env:
 TERM: xterm-256color

colors:
  primary:
    background: '#000000'

window:
 opacity: 0.6
 padding:
  x: 8
  y: 8

font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  size: 8

shell:
 program: /usr/bin/zsh
